<div class="container d-flex justify-content-center p-2">

    
    <form class="col" action="/consultar/store" method="post">
    <h1 class="h1"><?php echo $this->getPageTitle(); ?></h1>
        <div class="form-group">
            <label for="tipo">Tipo</label>
            <select type="text" name="tipo" class="form-control">
                <?php foreach ($this->view->tipo as $tipo) : ?>
                    <option value="<?php echo $tipo->tipo; ?>">
                        <?php echo $tipo->tipo; ?>
                    </option>
                <?php endforeach; ?>
            </select>
        </div>
        <div class="form-group">
            <label for="medida">Medida</label>
            <select type="text" name="medida" class="form-control">
                <?php foreach ($this->view->medida as $medida) : ?>
                    <option value="<?php echo $medida->medida; ?>">
                        <?php echo $medida->medida; ?>
                    </option>
                <?php endforeach; ?>
            </select>
        </div>
        <div class="form-group">
            <label for="recepiente">Recepiente</label>
            <select type="text" name="recepiente" class="form-control">
                <?php foreach ($this->view->recepiente as $recepiente) : ?>
                    <option value="<?php echo $recepiente->recepiente; ?>">
                        <?php echo $recepiente->recepiente; ?>
                    </option>
                <?php endforeach; ?>
            </select>
        </div>

        <div class="form-group">
            <label for="quantidade">Quantidade</label>
            <input type="text" name="quantidade" class="form-control" placeholder="Digite a quantidade" required  >
        </div>
        <div class="form-group p-1 d-flex justify-content-between" >
            <button type="submit" class="btn btn-primary col-2">Salvar</button>
            <a href="/consultar" class="btn btn-danger col-2">Cancelar</a>
        </div>
    </form>
</div>