<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="/assets/css/style.css">

    <title>Micro Framework</title>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto container">
            <li class="nav-item">
                <a class="nav-link" href="/">
                    <img src="/assets/img/cafe.png" class="pull-left p-1" width="30px" >Controle de consumo
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/consultar">Consultar</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/relatorio">Relatorio</a>
            </li>
            </ul>
        </div>
    </nav>
    <div class="container" >
        <div class="row" >
            <h1>Pagina não encontrada</h1>
        </div>
    </div>
    <script src="/assets/js/jquery.min.js"></script>
    <script src="/assets/js/bootstrap.min.js"></script>
</body>

</html>