<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="/assets/css/style.css">

    <title><?php $this->getPageTitle('-'); ?>Quantidade de cafe consumido diario</title>
  </head>
  <body>
    <?php require_once __DIR__. "/menu.phtml";
        $this->content();
    ?>
    <script src="/assets/js/jquery.min.js"></script>
    <script src="/assets/js/bootstrap.min.js"></script>
  </body>
</html>