<nav class="navbar navbar-expand-lg navbar-light bg-light p-2">
    <a class="navbar-brand p-0" href=""  >
        <img src="/assets/img/cafe.png" style="width:40px;height:40px;" >
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="/">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/consultar">Consultar</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/relatorio">Relatorio</a>
            </li>
        </ul>
    </div>
</nav>
